<?php
return [
  [
    'title' => '项目',
    'icon' => 'aicon ai-shezhi',
    'module' => 'test',
    'url' => 'test',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '首页',
        'icon' => 'aicon ai-shouyeshouye',
        'module' => 'test',
        'url' => 'test',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '城市列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'test',
            'url' => 'test/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '友情链接',
            'icon' => 'aicon ai-gongneng',
            'module' => 'test',
            'url' => 'test/link/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '分类标签',
        'icon' => 'aicon ai-cha',
        'module' => 'test',
        'url' => 'test',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '分类列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'test',
            'url' => 'test/category/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '标签管理',
            'icon' => 'aicon ai-gongneng',
            'module' => 'test',
            'url' => 'test/label/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '数据列表',
        'icon' => 'aicon ai-xitongrizhi-tiaoshi',
        'module' => 'test',
        'url' => 'test/data/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '数据列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'test',
            'url' => 'test/data/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
